### PR TITLE
fixing query to not have unecessary $and operation (which slows down query, markedly)

### PR DESCRIPTION
**Pull request by mateodelnorte**
addresses #171 speeds up queries when no filters are applied

sorry for the whitespace changes. relevant fix is lines 66 through 76 https://github.com/alethes/meteor-pages/pull/173/files?diff=unified#diff-c9d98e0288a31a447687782c7f212929R66

### CODE REVIEW

**Comment by anthonyserious** [comment]
+1.  Causes lots of COLLSCANs in mongo with empty conditions.

**Comment by andrewpmckenzie** [comment]
+1

**Comment by johannbotha** [comment]
+1

**Comment by mateodelnorte** [comment]
hi @alethes. note I had to change packages.js to allow us to install our fork locally, while this PR sits idle. you'll want to cherry pick the merge and merge everything but packages.js.

**Comment by mateodelnorte** [comment]
This pull request seems to have an issue against master, but the important lines https://github.com/alethes/meteor-pages/pull/173/files?diff=unified#diff-c9d98e0288a31a447687782c7f212929R66 made against 1.8.4 fix the heavy query.

**Pull request closed without merging**
